# Generated by Django 4.2.6 on 2023-11-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0003_book_geeksmodel_student_delete_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_birth', models.DateField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=600)),
                ('cgpa', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='book',
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
